name: Get dependencies & cache them
author: siarhkul
description: Get npm dependencies and cache them
inputs:
  caching:
    description: 'The caching strategy to use'
    default: 'true'
outputs:
  used-cache:
    description: 'Whether the cache was used'
    value: ${{ steps.install-id.outputs.cache-custom}}
runs:
  using: 'composite'
  steps:
    - name: Cache dependencies
      if: inputs.caching == 'true'
      id: cache
      uses: actions/cache@v3
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      id: install-id
      if: steps.cache.outputs.cache-hit != 'true' || inputs.caching != 'true'
      shell: bash
      run: |
        echo "${{toJson(steps)}}"
        npm ci
        echo "cache-custom ='${{inputs.caching}}'">>$GITHUB_OUTPUT
