name: Get dependencies & cache them
author: siarhkul
description: Get npm dependencies and cache them
inputs:
  caching:
    description: 'The caching strategy to use'
    default: 'true'

runs:
  using: 'composite'
  steps:
    - name: Cache dependencies
      if: inputs.caching == 'true'
      id: cache
      uses: actions/cache@v3
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true' || inputs.caching != 'true'
      shell: bash
      run: npm ci
