name: Deploy project
on:
  push:
    branches:
      - main
#    paths-ignore:
#      - '.github/workflows/**'
  workflow_dispatch: # Allows to run the workflow manually
    branches:
      - main
  pull_request:
    types:
      - opened
    branches:
      - main
jobs:
  test-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get the code
        uses: actions/checkout@v3
      - name: Install NodeJs
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
      - name: Run linter
        run: npm run lint

  build:
    runs-on: ubuntu-latest
    outputs:
      script-output: ${{ steps.publish.outputs.script-output}}
    steps:
      - name: Get the code
        uses: actions/checkout@v3
      - name: Install NodeJs
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm ci
      - name: Build project
        run: npm run build
      - name: Publish JS file
        id: publish
        run: find dist/apps/about/remoteEntry.js -type f -execdir echo 'script-output={}' >> $GITHUB_OUTPUT ';'
#        run:  find dist/apps/about/*.js -type f -execdir echo 'script-output={}' >> $GITHUB_OUTPUT ';'
#        run:  find dist/apps/about/*.js -type f -execdir echo '::set-output name=script-file::{}' ';'
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: dist-files
          path: dist

  deploy:
    needs: [ test-lint ,build ]
    runs-on: ubuntu-latest
    steps:
      - name: Get build artifact
        uses: actions/download-artifact@v3
        with:
          name: dist-files
#          path: dist
      - name: Output content of dist folder
        run: ls
      - name: Output files
        run: echo ${{ needs.build.outputs.script-output }}
      - name: Deploy
        run: |
          echo "Deploying the project..."
          echo "Done!"
