name: Issue information
on:
  issues:
    #types: [opened, edited, deleted]

jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: 'Output Github info'
        run: echo "${{toJson(github)}}"
