name: Deploy reusable workflow project
on:
  workflow_call:
    secrets:
      my_secret:
        required: true
    inputs:
      artifact-name:
        description: 'The name of the artifact to download'
        required: true
        default: 'dist'
        type: string
    outputs:
      result:
        description: 'The output of the reuseable workflow'
        value: ${{ jobs.change-me.outputs.outcome }}

jobs:
  change-me:
    runs-on: ubuntu-latest
    outputs:
      outcome: ${{steps.set-result-id.outputs.step-output}}
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
          path: dist
      - name: List files
        run: ls -l dist
      - name: Output ENV variables
        run: |
          echo "secret,${{ secrets.my_secret }}"
          echo "github objece,${{ toJson( github)}}"
      - name: Set result output
        id: set-result-id
        run: |
          echo "step-output=success" >> $GITHUB_OUTPUT
