name: Deploy reusable workflow project
on: workflow_call
jobs:
  change-me:
    runs-on: ubuntu-latest
    steps:
      - name: Output ENV variables
        run: |
          echo "github objece,${{github}}"
