name: Deploy reusable workflow project
on:
  workflow_call:
    inputs:
      artifact-name:
        description: 'The name of the artifact to download'
        required: true
        default: 'dist'
        type: string
    secrets:
      my_secret:
        required: true

jobs:
  change-me:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
          path: dist
      - name: List files
        run: ls -l dist
      - name: Output ENV variables
        run: |
          echo "secret,${{ secrets.my_secret }}"
          echo "github objece,${{ toJson( github)}}"
