name: Deploy reusable workflow project
on:
  push:
    branches:
      - main
jobs:
  test-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get the code
        uses: actions/checkout@v3
      - name: Install NodeJs
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Cache dependencies
        id: cache-id
        uses: actions/cache@v3
        with:
          path: node_modules
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        if: steps.cache-id.outputs.cache-hit != 'true'
        run: npm ci
      - name: Test code
        run: npm run test:coverage
      - name: Run linter
        run: npm run lint
      - name: Output ENV variables
        run: |
          echo "ENVs,${{env}}"
          echo "SECRET,${{secrets.NX_USER_SECRET}}"

  build:
    needs: [test-lint]
    runs-on: ubuntu-latest
    outputs:
      script-output: ${{ steps.publish.outputs.script-output}}
    steps:
      - name: Get the code
        uses: actions/checkout@v3
      - name: Install NodeJs
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Cache dependencies
        id: cache-id
        uses: actions/cache@v3
        with:
          path: node_modules
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        if: steps.cache-id.outputs.cache-hit != 'true'
        run: npm ci
      - name: Build project
        run: npm run build
      - name: Publish JS file
        id: publish
        run: find dist/apps/about/remoteEntry.js -type f -execdir echo 'script-output={}' >> $GITHUB_OUTPUT ';'
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact-mf
          path: dist
  deploy:
    needs: [build]
    uses: ./.github/workflows/reusable.yml
    with:
      artifact-name: 'build-artifact-mf'
